name: Tests

on: [push]

jobs:
  check:
    name: Tests
    runs-on: ${{ fromJSON(vars.CI_HOSTED == 'true' && '["ubuntu-latest"]' || '["self-hosted","Linux","X64","mini-linux-x64"]') }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvv
